export default function () {
  return {
    overview: 'Overview',
    control: 'Control',
    statistic: 'Statistics',
    setting: 'Setting',
    house_state: "House state",
    device_state: "Device state",
    control_panel: 'Control panel',
    temperature: 'Temperature',
    humidity: 'Humidity',
    lamp: 'Lamp',
    fan: 'Fan',
    curtain: 'Curtain',
    max: 'Max',
    min: 'Min',
    average: 'Average',
    on: 'On',
    off: 'Off',
    closed: 'Closed',
    language: 'Language',
    darkm: 'Dark mode',
    en: "English",
    vi: 'Vietnamese',
    fr: 'French',
    ger: 'German',
    span: 'Spanish',
    admin: 'Admin',
    fname: 'Full Name',
    abutton: 'Add Account',
    passwd: 'Password',
    cre: 'Add',
    back: 'Back'
  }
}