export default function () {
  return {
    overview: 'Descripción',
    control: 'Control',
    statistic: 'Estadísticas',
    setting: 'Ajuste',
    house_state: "Estado de la casa",
    device_state: "Estado del dispositivo",
    control_panel: 'Panel de control',
    temperature: 'Temperatura',
    humidity: 'Humedad',
    lamp: 'Lámpara',
    fan: 'Ventilador',
    curtain: 'Cortina',
    max: 'Máx',
    min: 'Mínimo',
    average: 'Promedio',
    on: 'Encendida',
    off: 'Apagada',
    closed: 'Cerrada',
    language: 'Idioma',
    darkm: 'Modo Oscuro',
    en: "Inglés",
    vi: 'vietnamita',
    fr: 'Francés',
    ger: 'Alemán',
    span: 'Español',
    admin: 'Administrador',
    fname: 'Nombre completo',
    abutton: 'Añadir cuenta',
    passwd: 'Contraseña',
    cre: 'Agregar',
    back: 'Atrás'
  }
}