# Stage 1: Install dependency

FROM node:alpine as builder

WORKDIR /app

COPY --chown=node:node package*.json ./
RUN npm install --save-dev

# Stage 2: Copy/Mount backend folder to container

FROM node:alpine
ENV NODE_ENV=development

EXPOSE 3030

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node . .
COPY --from=builder /app/node_modules /home/node/app/app_modules

RUN npm i @nestjs/cli
CMD ["yarn", "run", "start:dev"]