export default function () {
  return {
    overview: 'Aperçu',
    control: 'Contrôle',
    statistic: 'Statistique',
    setting: 'Paramètre',
    house_state: "État de la maison",
    device_state: "État de l'appareil",
    control_panel: 'Panneau de commande',
    temperature: 'Température',
    humidity: 'Humidité',
    lamp: 'Lampe',
    fan: 'Ventilateur',
    curtain: 'Rideau',
    max: 'Max',
    min: 'Min',
    average: 'Moyenne',
    on: 'Allumée',
    off: 'Éteinte',
    closed: 'Fermée',
    language: 'Langue',
    darkm: 'Mode sombre',
    en: "Anglais",
    vi: 'Vietnamien',
    fr: 'Français',
    ger: 'Allemand',
    span: 'Espagnol',
    admin: 'Administrateur',
    fname: 'Nom et prénom',
    abutton: 'Ajouter un compte',
    passwd: 'Mot de passe',
    cre: 'Ajouter',
    back: 'Arrière',
    speaker: 'Sirène',
    gas: 'Concentration de gaz',
    h1: '1 Heure',
    h2: '2 Heures',
    h6: '6 Heures',
    h12: '12 Heures',
    d1: '1 Jour',
    w1: '1 Semaine',
    m1: '1 Mois'
  }
}