export default function () {
  return {
    overview: 'Überblick',
    control: 'Kontrolle',
    statistic: 'Statistik',
    setting: 'Einstellung',
    house_state: "Hauszustand",
    device_state: "Gerätezustand",
    control_panel: 'Schalttafel',
    temperature: 'Temperatur',
    humidity: 'Feuchtigkeit',
    lamp: 'Lampe',
    fan: 'Ventilator',
    curtain: 'Vorhang',
    max: 'Max',
    min: 'Min',
    average: 'Durchschnitt',
    on: 'An',
    off: 'Aus',
    closed: 'Geschlossen',
    language: 'Sprache',
    darkm: 'Dunkler Modus',
    en: "Englisch",
    vi: 'Vietnamesisch',
    fr: 'Französisch',
    ger: 'Deutsch',
    span: 'Spanisch',
    admin: 'Administrator',
    fname: 'Vollständiger Name',
    abutton: 'Konto hinzufügen',
    passwd: 'Passwort',
    cre: 'Addieren',
    back: 'Zurück',
    speaker: 'Sirene',
    gas: 'Gaskonzentration',
    h1: '1 Stunde',
    h2: '2 Stunden',
    h6: '6 Stunden',
    h12: '12 Stunden',
    d1: '1 Tag',
    w1: '1 Woche',
    m1: '1 Monat'
  }
}