export default function () {
  return {
    overview: 'Überblick',
    control: 'Kontrolle',
    statistic: 'Statistik',
    setting: 'Einstellung',
    house_state: "Hauszustand",
    device_state: "Gerätezustand",
    control_panel: 'Schalttafel',
    temperature: 'Temperatur',
    humidity: 'Feuchtigkeit',
    gas: 'Gas',
    lamp: 'Lampe',
    fan: 'Ventilator',
    curtain: 'Vorhang',
    buzzer: 'Gasexplosionssummer',
    max: 'Max',
    min: 'Min',
    average: 'Durchschnitt',
    on: 'An',
    off: 'Aus',
    closed: 'Geschlossen',
    language: 'Sprache',
    darkm: 'Dunkler Modus',
    en: "Englisch",
    vi: 'Vietnamesisch',
    fr: 'Französisch',
    ger: 'Deutsch',
    span: 'Spanisch',
    admin: 'Administrator',
    fname: 'Vollständiger Name',
    abutton: 'Konto hinzufügen',
    passwd: 'Passwort',
    cre: 'Addieren',
    back: 'Zurück'
  }
}