export default function () {
  return {
    overview: 'Tổng quan',
    control: 'Điều khiển',
    statistic: 'Thống kê',
    setting: 'Cài đặt',
    house_state: "Trạng thái nhà",
    device_state: "Trạng thái thiết bị",
    control_panel: 'Bảng điều khiển',
    temperature: 'Nhiệt độ',
    humidity: 'Độ ẩm',
    lamp: 'Đèn',
    fan: 'Quạt',
    curtain: 'Rèm',
    max: 'Cao nhất',
    min: 'Thấp nhất',
    average: 'Trung bình',
    on: 'Mở',
    off: 'Tắt',
    closed: 'Đóng',
    language: 'Ngôn ngữ',
    darkm: 'Giao diện tối',
    en: "Tiếng Anh",
    vi: 'Tiếng Việt',
    fr: 'Tiếng Pháp',
    ger: 'Tiếng Đức',
    span: 'Tiếng Tây Ban Nha',
    admin: 'Quản Trị',
    fname: 'Tên đăng nhập',
    abutton: 'Thêm Tài Khoản',
    passwd: 'Mật Khẩu',
    cre: 'Thêm',
    back: 'Trở Lại',
    buzzer: 'Loa',
    gas: 'Nồng độ gas',
    h1: '1 Giờ',
    h2: '2 Giờ',
    h6: '6 Giờ',
    h12: '12 Giờ',
    d1: '1 Ngày',
    w1: '1 Tuần',
    m1: '1 Tháng'
  }
}